### ISSUE TITLE
Linking to libatomic is required on 32-bit platforms

### ISSUE THREAD

**Issue by barracuda156** [stla/lazyNumbers#2]
```
/opt/local/bin/g++-mp-12 -std=gnu++17 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/opt/local/Library/Frameworks/R.framework/Resources/lib -Wl,-headerpad_max_install_names -Wl,-rpath,/opt/local/lib/libgcc -L/opt/local/lib -lMacportsLegacySupport -arch ppc -o lazyNumbers.so RcppExports.o lazyNumbers.o -L/opt/local/lib -lgmp -lmpfr -lgmp -F/opt/local/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
installing to /opt/local/var/macports/build/_opt_PPCRosettaPorts_R_R-lazyNumbers/R-lazyNumbers/work/lazyNumbers/lazyNumbers.Rcheck/00LOCK-lazyNumbers/00new/lazyNumbers/libs
** R
** byte-compile and prepare package for lazy loading
Creating a generic function for ‘diag’ from package ‘base’ in package ‘lazyNumbers’
Creating a generic function for ‘diag<-’ from package ‘base’ in package ‘lazyNumbers’
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘lazyNumbers’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/opt/local/var/macports/build/_opt_PPCRosettaPorts_R_R-lazyNumbers/R-lazyNumbers/work/lazyNumbers/lazyNumbers.Rcheck/00LOCK-lazyNumbers/00new/lazyNumbers/libs/lazyNumbers.so':
  dlopen(/opt/local/var/macports/build/_opt_PPCRosettaPorts_R_R-lazyNumbers/R-lazyNumbers/work/lazyNumbers/lazyNumbers.Rcheck/00LOCK-lazyNumbers/00new/lazyNumbers/libs/lazyNumbers.so, 6): Symbol not found: ___atomic_load_8
  Referenced from: /opt/local/var/macports/build/_opt_PPCRosettaPorts_R_R-lazyNumbers/R-lazyNumbers/work/lazyNumbers/lazyNumbers.Rcheck/00LOCK-lazyNumbers/00new/lazyNumbers/libs/lazyNumbers.so
  Expected in: dynamic lookup

Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/opt/local/var/macports/build/_opt_PPCRosettaPorts_R_R-lazyNumbers/R-lazyNumbers/work/lazyNumbers/lazyNumbers.Rcheck/lazyNumbers’
```

**Comment by barracuda156** [comment]
After this and another error https://github.com/stla/lazyNumbers/issues/1 are fixed, all tests pass:
```
--->  Testing R-lazyNumbers
* using log directory ‘/opt/local/var/macports/build/_opt_PPCRosettaPorts_R_R-lazyNumbers/R-lazyNumbers/work/lazyNumbers/lazyNumbers.Rcheck’
* using R version 4.2.3 (2023-03-15)
* using platform: powerpc-apple-darwin10.8.0 (32-bit)
* using session charset: UTF-8
* checking for file ‘lazyNumbers/DESCRIPTION’ ... OK
* checking extension type ... Package
* this is package ‘lazyNumbers’ version ‘1.2.1’
* package encoding: UTF-8
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking for sufficient/correct file permissions ... OK
* checking whether package ‘lazyNumbers’ can be installed ... OK
* checking installed package size ... OK
* checking package directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking loading without being on the library search path ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... OK
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking line endings in shell scripts ... OK
* checking line endings in C/C++/Fortran sources/headers ... OK
* checking line endings in Makefiles ... OK
* checking compilation flags in Makevars ... OK
* checking for GNU extensions in Makefiles ... OK
* checking for portable use of $(BLAS_LIBS) and $(LAPACK_LIBS) ... OK
* checking use of PKG_*FLAGS in Makefiles ... OK
* checking compiled code ... OK
* checking examples ... OK
* checking for unstated dependencies in ‘tests’ ... OK
* checking tests ...
  Running ‘testthat.R’
 OK
* checking PDF version of manual ... OK
* DONE

Status: OK
```

**Comment by stla** [comment]
I didn't know 32-bit platforms still exist... 

This package passes all the CRAN tests.

**Comment by barracuda156** [comment]
> I didn't know 32-bit platforms still exist... 
> 
> This package passes all the CRAN tests.

I think CRAN has none simply, not even i386, forget ppc or mips.

The fix is trivial – to pass `-latomic` flag. It is possible to either write a test for atomics without/with `libatomic` linking and add flags accordingly or do it in a simpler way, conditional on compiler being GCC and 4-byte pointers (or even just GCC).
